FROM ubuntu:latest
MAINTAINER hiroyakubo

ENV USER ubuntu

RUN apt update
RUN apt install -y sudo \
                   python3-dev \
                   python3-pip \
                   vim

RUN pip3 install django==2.2 \
                 django-debug-toolbar \
                 pillow

RUN useradd -m ${USER}
RUN gpasswd -a ${USER} sudo
RUN echo "${USER}:password" | chpasswd

USER ${USER}
WORKDIR /home/ubuntu